### ISSUE TITLE
Insert Larger Collection of Recipes into Database

### ISSUE THREAD

**Issue by Acesonnall** [Acesonnall/PotLuck#14]
534 recipes is not a lot when trying to make recommendations. Let's up it to at least 5K.

**Comment by cghubbard** [comment]
When you get the list of unique recipes let @soupAgni and I know.  We will get you similarities.  Did we decide on a max number of similarities for importance sampling?

**Comment by Acesonnall** [comment]
I don't remember if we did. I currently have it set to Math.round(length of similarities array/10) -- an arbitrary calculation that typically results in a max number of 10 since the length is always 90.

Any ideas of a better determination for the max?

**Comment by Acesonnall** [comment]
@yaokasha My lastest commit of the GetRandRecipe script will help you complete this faster.

**Comment by Acesonnall** [comment]
There are now 1011 recipes in the database with corresponding similarities.
